# Generated by Django 5.1.6 on 2025-02-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='birht_date',
            field=models.TextField(blank=True),
        ),
    ]
