# Generated by Django 5.1.6 on 2025-02-23 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0002_carmodel_birht_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='birht_date',
            new_name='birth_date',
        ),
    ]
