# Generated by Django 5.1.6 on 2025-02-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0003_rename_birht_date_carmodel_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='context',
            field=models.TextField(blank=True),
        ),
    ]
