# Generated by Django 5.1.6 on 2025-02-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0004_carmodel_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='photo',
            field=models.ImageField(default=0, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
